### ISSUE TITLE
java.lang.NoClassDefFoundError: buildcraft/factory/BlockQuarry

### ISSUE THREAD

**Issue by Tsyklop** [UniversalRed/BuildTech#3]
Crash. http://pastebin.com/XpZ0hZ4C
1.7.10

**Comment by UniversalRed** [comment]
It's been a while since I've made that release (two years to be precise), but if memory serves me correctly, that version of BuildTech was only for BC Next Gen 6.x.x (or whatever it was), not for BC 7.1.16 as I released BuildTech-R1.0.2 before the module system was introduced. Sorry if that is an inconvenience, maybe I can learn from this by adding the required BC version for future BuildTech releases to avoid confusion.

**Comment by Tsyklop** [comment]
Okay. Thanks
